### PR TITLE
Fix mission definition filter and prevent duplicate mission definitions

### LINKED ISSUE #984: Do not create a new source blob if one with the same hash already exists
**Describe the improvement you would like to see**
We want to store the hash in the source object for custom sources, maybe as the ID value. We can then check if there already exists a source object for the tasks we are trying to upload again.

**How will this change existing functionality?**
This will prevent duplicate source objects, as well as duplicate blobs. 

**How will this improvement affect the current Threat Model?**
N/A

### PR DESCRIPTION
**Pull request by andchiind**
Closes #984

### CODE REVIEW

File: backend/api/Controllers/MissionController.cs [hunk 1]
```diff
@@ -384,14 +385,27 @@ public async Task<ActionResult<byte[]>> GetMap([FromRoute] string installationCo
...
+        var source = await _sourceService.CheckForExistingEchoSource(scheduledMissionQuery.EchoMissionId);
+        MissionDefinition? existingMissionDefinition = null;
+        if (source == null)
         {
-            Id = Guid.NewGuid().ToString(),
-            Source = new Source
+            source = new Source
             {
-                SourceId = $"{echoMission.Id}",
+                SourceId = $"{scheduledMissionQuery.EchoMissionId}",
```
Comment (andchiind) [inline backend/api/Controllers/MissionController.cs:394]: The returned echoMission is a mock when running the unit tests which is why we don't want to reference it here, but scheduledMissionQuery.EchoMissionId and echoMission.Id should always be the same here regardless.

File: backend/api.test/Mocks/CustomMissionServiceMock.cs [hunk 2]
```diff
@@ -29,5 +32,20 @@ public string UploadSource(List<MissionTask> tasks)
             }
             return null;
         }
+
+        public string CalculateHashFromTasks(IList<MissionTask> tasks)
```
[the remark this answers is not in the document]
Comment (Afonso-2403) [reply backend/api.test/Mocks/CustomMissionServiceMock.cs:36]: I see that it makes it easier to have it this way instead of then also mocking the retrieving of tasks in `GetMissionTasksFromSourceId`

File: backend/api.test/EndpointTest.cs [hunk 3]
```diff
@@ -702,5 +706,141 @@ public async Task GetNextRun()
             Assert.Equal(missionRun3.MissionId, missionRun.MissionId);
             Assert.True(nextMissionRun.Id == missionRun2.Id);
         }
+
+        [Fact]
+        public async Task ScheduleDuplicateCustomMissionDefinitions()
```
Comment (Afonso-2403) [inline backend/api.test/EndpointTest.cs:711]: For this test (and others) shouldn't `StidService` also be mocked?

File: backend/api/Controllers/MissionController.cs (hunk 1 above)
Comment (Afonso-2403) [reply backend/api/Controllers/MissionController.cs:394]: I am not a big fan of altering functionality to fit tests, but agree that here there is no problem, this will be brought up in the discussion related to how we structure our tests

Comment (andchiind) [reply backend/api/Controllers/MissionController.cs:394]: I'm looking into making the mock handle this regardless.

Comment (andchiind) [reply backend/api/Controllers/MissionController.cs:394]: image
This approach lets us avoid this change on line 394, but I'm not sure if it is more elegant.

File: backend/api/Controllers/SourceController.cs [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+
+        return Ok(sources);
+    }
+
+    /// <summary>
+    /// Lookup a custom source by specified id.
+    /// </summary>
+    [HttpGet]
+    [Authorize(Roles = Role.Any)]
+    [Route("{id}/custom")]
```
Comment (Afonso-2403) [inline backend/api/Controllers/SourceController.cs:78]:
```suggestion
    [Route("custom/{id}")]
```
To be in accordance with the other controllers

File: backend/api/Services/SourceService.cs [hunk 5]
```diff
@@ -0,0 +1,185 @@
...
+        public async Task<Source?> ReadBySourceId(string sourceId)
+        {
+            return await GetSources()
+                .FirstOrDefaultAsync(s => s.SourceId.Equals(sourceId));
+        }
+
+        public async Task<SourceResponse?> ReadByIdAndInstallationWithTasks(string id, string installationCode)
+        {
+            var source = await GetSources()
+                .FirstOrDefaultAsync(a => a.Id.Equals(id));
```
Comment (Afonso-2403) [inline backend/api/Services/SourceService.cs:92]:
```suggestion
                .FirstOrDefaultAsync(s => s.Id.Equals(id));
```

File: backend/api/Services/SourceService.cs [hunk 6]
```diff
@@ -0,0 +1,185 @@
...
+                    return new SourceResponse(source, tasks);
+                default:
+                    return null;
+            }
+        }
+
+        public async Task<SourceResponse?> ReadByIdWithTasks(string id)
+        {
+            var source = await GetSources()
+                .FirstOrDefaultAsync(a => a.Id.Equals(id));
```
Comment (Afonso-2403) [inline backend/api/Services/SourceService.cs:117]:
```suggestion
                .FirstOrDefaultAsync(s => s.Id.Equals(id));
```

**Review by Afonso-2403 — APPROVED** [review]
Don't merge before #970 is merged, then fix the warnings of possible null reference
