### PR TITLE
Disable schedule mission button when no robots available

### LINKED ISSUE #1182: Add mission buttons available even if no robot is in the installation
**Describe the bug**
If we select an istallation with no robots, the buttons to add mission/create mission in echo are still visible. Should we maybe disable them if no robots are in the installation?

**To Reproduce**
Just select Bacalhau or another installation and look at the add mission buttons on the bottom of the mission queue.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by andchiind**
Closes #1182 
Also refactors the files related to it. It is best to check the PR commit by commit, since most of them are just refactoring. Some commits have more than one lines in their commit message.

### CODE REVIEW

File: frontend/src/components/Contexts/MissionListsContext.tsx [hunk 1]
```diff
@@ -142,13 +175,15 @@ export const useMissions = (): MissionsResult => {
         // eslint-disable-next-line react-hooks/exhaustive-deps
     }, [BackendAPICaller.accessToken])
```
Comment (Eddasol) [inline frontend/src/components/Contexts/MissionListsContext.tsx:176]: Currently missionDefinitions don't show initially and on reload. Adding equivalent useEffect with API-call like this above solves that

File: frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx [hunk 2]
```diff
@@ -14,6 +14,7 @@ import { useRobotContext } from 'components/Contexts/RobotContext'
 import { AlertType, useAlertContext } from 'components/Contexts/AlertContext'
 import { EchoMissionDefinition } from 'models/MissionDefinition'
 import { FailedRequestAlertContent } from 'components/Alerts/FailedRequestAlert'
+import { StyledDict } from './InspectionUtilities'
 import { Icons } from 'utils/icons'
 
 const StyledContent = styled.div`
```
Comment (Eddasol) [inline frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx:20]: Should APIcall on line 51 also be switched out with the missionContext?

File: frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx [hunk 3]
```diff
@@ -123,7 +112,15 @@ export const InspectionOverviewSection = () => {
                                 <AddPredefinedMissionsButton />
                                 <CreateEchoMissionButton />
                             </StyledButtons>
-                            {allMissions && <AllInspectionsTable inspections={allMissions} />}
+                            {allInspections && allInspections.length > 0 ? (
```
Comment (Eddasol) [inline frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx:115]:
```suggestion
                            {allInspections.length > 0 ? (
```
allInspections cannot be undefined so this should be the same

File: frontend/src/components/Pages/InspectionPage/InspectionTable.tsx [hunk 4]
```diff
@@ -92,12 +94,19 @@ interface IInspectionRowProps {
...
     const mission = inspection.missionDefinition
     let status
     let lastCompleted: string = ''
     const isScheduled = missionQueue.map((m) => m.missionId).includes(mission.id)
     const isOngoing = ongoingMissions.map((m) => m.missionId).includes(mission.id)
 
+    const isScheduleButtonDisabled =
+        !enabledRobots ||
+        enabledRobots.filter((r) => r.currentInstallation.installationCode === installationCode).length === 0 ||
+        installationCode === ''
```
Comment (Eddasol) [inline frontend/src/components/Pages/InspectionPage/InspectionTable.tsx:108]:
```suggestion
    const isScheduleButtonDisabled =
        enabledRobots.filter((r) => r.currentInstallation.installationCode === installationCode).length === 0 ||
        installationCode === ''
```

File: frontend/src/components/Pages/InspectionPage/InspectionUtilities.tsx [hunk 5]
```diff
@@ -1,6 +1,6 @@
 import { Card, Typography } from '@equinor/eds-core-react'
 import styled from 'styled-components'
-import { DeckMissionCount, Inspection } from './InspectionSection'
```
Comment (Eddasol) [inline frontend/src/components/Pages/InspectionPage/InspectionUtilities.tsx:3]: Nothing else is using DeckMissionCount so it can be deleted in inspectionSection

File: frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx [hunk 6]
```diff
@@ -123,7 +124,15 @@ export const InspectionOverviewSection = () => {
...
                             </StyledButtons>
-                            {allMissions && <AllInspectionsTable inspections={allMissions} />}
+                            {allMissions && allMissions.length > 0 ? (
+                                <AllInspectionsTable inspections={allMissions} />
+                            ) : (
+                                <StyledDict.Placeholder>
+                                    <Typography variant="h4" color="disabled">
+                                        {TranslateText('No predefined missions available')}
+                                    </Typography>
+                                </StyledDict.Placeholder>
```
[the remark this answers is not in the document]
Comment (Eddasol) [reply frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx:122]: image
Would prefer if the placeholder got moved left without affecting the existing design where the buttons are right

File: frontend/src/components/Contexts/SignalRContext.tsx [hunk 7]
```diff
@@ -103,6 +103,7 @@ export enum SignalREventLabels {
     missionRunUpdated = 'Mission run updated',
     missionDefinitionCreated = 'Mission definition created',
     missionDefinitionUpdated = 'Mission definition updated',
+    missionDefinitionDeleted = 'Mission definition deleted',
```
[the remark this answers is not in the document]
Comment (andchiind) [reply frontend/src/components/Contexts/SignalRContext.tsx:106]: I don't think there's any harm in having it, personally, since we might use it in the future.

File: frontend/src/components/Pages/InspectionPage/InspectionTable.tsx [hunk 8]
```diff
@@ -177,6 +187,7 @@ const InspectionRow = ({ inspection, openDialog, setMissions, openScheduledDialo
                 {isScheduled && (
                     <Button
                         variant="ghost_icon"
+                        disabled={!enabledRobots || enabledRobots.length === 0}
```
Comment (Eddasol) [inline frontend/src/components/Pages/InspectionPage/InspectionTable.tsx:190]:
```suggestion
                        disabled={isScheduleButtonDisabled}
```

File: frontend/src/components/Pages/InspectionPage/InspectionTable.tsx [hunk 9]
```diff
@@ -161,6 +170,7 @@ const InspectionRow = ({ inspection, openDialog, setMissions, openScheduledDialo
                 {!isScheduled && (
                     <Button
                         variant="ghost_icon"
+                        disabled={isScheduleButtonDisabled}
```
Comment (Eddasol) [inline frontend/src/components/Pages/InspectionPage/InspectionTable.tsx:173]: Suggest adding some kind of user feedback when button is disabled informing why it's disabled

File: frontend/src/components/Pages/InspectionPage/InspectionTable.tsx [hunk 10]
```diff
@@ -92,12 +94,18 @@ interface IInspectionRowProps {
...
     const { ongoingMissions, missionQueue } = useMissionsContext()
+    const { installationCode } = useInstallationContext()
+    const { enabledRobots } = useRobotContext()
     const mission = inspection.missionDefinition
     let status
     let lastCompleted: string = ''
     const isScheduled = missionQueue.map((m) => m.missionId).includes(mission.id)
     const isOngoing = ongoingMissions.map((m) => m.missionId).includes(mission.id)
 
+    const isScheduleButtonDisabled =
```
Comment (Eddasol) [inline frontend/src/components/Pages/InspectionPage/InspectionTable.tsx:105]: Should there also be disable on "Queue the missions" on deckCards?

File: frontend/src/components/Pages/InspectionPage/ScheduleMissionDialogs.tsx [hunk 11]
```diff
@@ -78,29 +74,13 @@ export const ScheduleMissionDialog = (props: IProps): JSX.Element => {
...
 
     const onSelectedRobot = (selectedRobot: Robot) => {
-        if (!robotOptions) return
-
-        setSelectedRobot(selectedRobot)
+        if (robotOptions) setSelectedRobot(selectedRobot)
     }
 
-    const onScheduleButtonPress = () => {
+    const onScheduleButtonPress = (missions: CondensedMissionDefinition[]) => () => {
```
[the remark this answers is not in the document]
Comment (andchiind) [reply frontend/src/components/Pages/InspectionPage/ScheduleMissionDialogs.tsx:80]: The error was actually made in a rebase further down in the file. It should be:
image
instead of 
image

File: frontend/src/components/Pages/InspectionPage/InspectionTable.tsx (hunk 9 above)
Comment (andchiind) [reply frontend/src/components/Pages/InspectionPage/InspectionTable.tsx:172]: I can add a tooltip

Comment (andchiind) [reply frontend/src/components/Pages/InspectionPage/InspectionTable.tsx:172]: Or maybe some red text

Comment (andchiind) [reply frontend/src/components/Pages/InspectionPage/InspectionTable.tsx:174]: I have added tooltips and texts where convenient

File: frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx [hunk 12]
```diff
@@ -0,0 +1,258 @@
...
+const PressureDialog = ({ setIsCheckConfirmed, robot, deckName }: CheckDialogProps) => {
+    const { TranslateText } = useLanguageContext()
+
+    let statusText = ''
+    if (robot.pressureLevel) {
+        if (
+            robot.pressureLevel > robot.model.lowerPressureWarningThreshold &&
+            robot.pressureLevel < robot.model.upperPressureWarningThreshold
+        ) {
+            statusText = `${TranslateText('The current pressure level is')} ${robot.pressureLevel}
```
Comment (Eddasol) [inline frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx:77]: Missing translation

File: frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx [hunk 13]
```diff
@@ -0,0 +1,258 @@
...
+                            ${TranslateText('which is within the suggested range')}`
+        } else {
+            statusText = `${TranslateText('Warning')}: ${TranslateText('The current pressure level is')} ${
```
Comment (Eddasol) [inline frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx:80]: Missing translation

File: frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx [hunk 14]
```diff
@@ -0,0 +1,258 @@
...
+                robot.pressureLevel
+            }
+                            ${TranslateText('which is NOT within the suggested range')}`
```
Comment (Eddasol) [inline frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx:83]: Missing translation

File: frontend/src/components/Contexts/InstallationContext.tsx [hunk 15]
```diff
@@ -23,16 +28,23 @@ interface Props {
 const defaultInstallation = {
     installationCode: '',
     installationName: '',
+    installationDecks: [],
+    installationAreas: [],
```
Comment (mrica-equinor) [inline frontend/src/components/Contexts/InstallationContext.tsx:32]: I quite like this idea of having most things related to an installation in the installation context

File: frontend/src/components/Contexts/MissionRunsContext.tsx [hunk 16]
```diff
@@ -4,14 +4,13 @@ import { BackendAPICaller } from 'api/ApiCaller'
 import { SignalREventLabels, useSignalRContext } from './SignalRContext'
 import { translateSignalRMission } from 'utils/EnumTranslations'
 
-const upsertList = (list: Mission[], mission: Mission) => {
+const upsertMissionList = (list: Mission[], mission: Mission) => {
     let newList = [...list]
     const i = newList.findIndex((e) => e.id === mission.id)
     if (i > -1) newList[i] = mission
     else newList.push(mission)
     return newList
```
Comment (mrica-equinor) [inline frontend/src/components/Contexts/MissionRunsContext.tsx:12]: how do you feel about calling this newMissionList to keep the same line of thought?

File: frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx [hunk 17]
```diff
@@ -0,0 +1,256 @@
...
+    return (
+        <>
+            <Dialog.Header>
+                <Typography variant="h5">{TranslateText('Confirm placement of robot')}</Typography>
+            </Dialog.Header>
+            <Dialog.Content>
+                <VerticalContent>
+                    <Typography>
+                        {`${robot.name} (${robot.model.type}) ${TranslateText(
+                            'needs to be placed on marked position on'
```
Comment (mrica-equinor) [inline frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx:37]: I want to change this to must but think that's scope creep and i can do that another time. Also below the english can be sinplified and more straight to the point

File: frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx [hunk 18]
```diff
@@ -0,0 +1,256 @@
...
+                'which is within the suggested range'
+            )}`
+        } else {
+            statusText = `${TranslateText('Warning')}: ${TranslateText('The current pressure level is')} ${
+                robot.pressureLevel
+            } ${TranslateText('which is NOT within the suggested range')}`
+        }
+    } else {
+        statusText = TranslateText(
+            'The pressure measurement is not currently available, so start the mission at your own risk.'
```
Comment (mrica-equinor) [inline frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx:82]: This is funny but we can't have this text either ahaha i'll do a PR on this later today

File: frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx [hunk 19]
```diff
@@ -0,0 +1,256 @@
...
+    )
+}
+
+const PressureDialog = ({ setIsCheckConfirmed, robot, deckName }: CheckDialogProps) => {
+    const { TranslateText } = useLanguageContext()
+
+    let statusText = ''
+    if (robot.pressureLevel) {
+        if (
+            robot.pressureLevel > robot.model.lowerPressureWarningThreshold &&
```
Comment (mrica-equinor) [inline frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx:69]: image

pressure is being compared in different unit of measurement

File: frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx [hunk 20]
```diff
@@ -0,0 +1,256 @@
...
+    const { TranslateText } = useLanguageContext()
+
+    let statusText = ''
+    if (robot.batteryLevel) {
+        if (!robot.model.batteryWarningThreshold || robot.batteryLevel > robot.model.batteryWarningThreshold) {
+            statusText = `${TranslateText('The current battery level is')} ${robot.pressureLevel}
+                            ${TranslateText('which is above the suggested minimum')}`
+        } else {
+            statusText = `${TranslateText('Warning')}: ${TranslateText('The current battery level is')} ${
+                robot.pressureLevel
```
Comment (mrica-equinor) [inline frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx:130]: image

battery level is being compared with robot.pressure

File: frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx (hunk 17 above)
Comment (andchiind) [reply frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx:37]: This text is copied from how it was before, so I hope it's okay to leave it and the other rewordings for another PR?

Comment (mrica-equinor) [reply frontend/src/components/Displays/LocalizationVerification/ScheduleMissionChecklistDialog.tsx:37]: Yeah yeah, that's what i was thinking don't worry about it, just commented so i can find this code later when we work on the next PR

File: frontend/src/language/no.json [hunk 21]
```diff
@@ -204,5 +204,22 @@
...
+    "and": "og",
+    "The battery measurement is not currently available, so start the mission at your own risk.": "Batterimålingen er ikke tilgjengelig, så start oppdraget på egen risiko.",
+    "has a pressure level making it safe for the area it is operating in": "har et trykkinivå som gjør det trykt i området den kjører i",
+    "has a battery level making it safe for the area it is operating in": "har et batterinivå som gjør det trykt i området den kjører i",
+    "needs to be have a battery level greater than": "trenger å ha et batterinivå større enn",
+    "Confirm battery level of robot": "Bekreft batterinivået til roboten",
+    "The current pressure level is": "Trykknivået er nå",
+    "which is within the suggested range": "som er innenfor den anbefalte rekkevidden",
+    "Warning": "Advarsel",
+    "which is NOT within the suggested range": "som IKKE er innenfor den anbefalte rekkevidden"
```
Comment (mrica-equinor) [inline frontend/src/language/no.json:224]: image

missing translations

Comment (mrica-equinor) [reply frontend/src/language/no.json:224]: image

**Review by mrica-equinor — APPROVED** [review]
LGTM :)
