### PR TITLE
Translate autocomplete placeholder

### LINKED ISSUE #890: Autocomplete placeholder is always in english
**Describe the bug**
For autocomplete components with multiple options it says "x/y selected" even if language is set to Norwegian

**To Reproduce**

**Expected behavior**
Should say something like "x/y valgte" when selecting Norwegian as language

**Suggested solution**
E.g. set the placeholder value to:
`placeholder = {'${numberOfSelectedObjects}/${numberOfObjects} ${TranslateText('selected')}'}`

**Screenshots**
image

### PR DESCRIPTION
**Pull request by andchiind**
Closes #890

### CODE REVIEW

File: frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx [hunk 1]
```diff
@@ -156,6 +156,7 @@ export function MissionQueueView({ refreshInterval }: RefreshProps) {
                     robotOptions={Array.from(robotOptions.keys())}
                     echoMissionsOptions={Array.from(echoMissions.keys())}
                     onSelectedMissions={onSelectedEchoMissions}
```
Comment (mrica-equinor) [inline frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx:158]: im a bit confused here, do we still use the line 158? they have very similar names, can we change to make it more clear or merge them together?

Comment (andchiind) [reply frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx:158]: We still use 158 since 158 is the one that changes the selected echo missions that are passed on line 159. But I'll rename them

**Review by mrica-equinor — APPROVED** [review]
LGTM :)
