### PR TITLE
Fix confirmation button asset page

### LINKED ISSUE #1124: "Confirm installation" is disabled when the input is valid
**Describe the bug**
The "Confirm installation" button is initially disabled on assetSelectionPage. Even if the previously selected value is valid.

**To Reproduce**
1. Go to assetSelectionPage
2. If the selected value is invalid, select a valid one and repeat step 1
3. Note that the button "Confirm installation" is disabled
4. Click on the dropdown and note that the button is active

**Expected behavior**
The button should not be disabled if the value is valid, and it shouldn't be necessary to re-select the same value before confirming

**Screenshots**
Asset selection page with "Confirm installation" disabled - even though the selected value is valid
image

Asset selection page after clicking the dropdown. The value is not changed but the button becomes active
image

### PR DESCRIPTION
**Pull request by mrica-equinor**
Closes #1124

### CODE REVIEW

File: frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx [hunk 1]
```diff
@@ -137,7 +134,7 @@ function InstallationPicker() {
             </BlockLevelContainer>
             <Button
                 onClick={() => switchInstallation(selectedInstallation)}
-                disabled={!validateInstallation(selectedInstallation)}
+                disabled={!selectedInstallation}
```
Comment (andchiind) [inline frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx:137]: Without this check we can accept any non-empty string 
image

**Review by andchiind — CHANGES_REQUESTED** [review]

File: frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx (hunk 1 above)
Comment (mrica-equinor) [reply frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx:137]: Hum i dind't try that indeed, thanks!

**Review by andchiind — APPROVED** [review]
I was sadly not able to break it
