### PR TITLE
Display azure videostream

### LINKED ISSUE #468: Video stream command bar exceeds VideoStreamWindow card
**Describe the bug**
Video stream command bar exceeds VideoStreamWindow such that "full screen"-button is hidden outside of the card. 

**To Reproduce**
Start flotilla --> Navigate to Mission page to see video stream

**Expected behavior**
Video stream command bar fully visible inside card.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by phhuseboe**
Closes #468

### CODE REVIEW

File: frontend/src/components/VideoStream/Video.tsx [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+const VideoPlayer: FC<IVideoPlayerProps> = ({ options }) => {
+    const player = useRef<videojs.Player>()
+
+    useEffect(() => {
+        player.current = videojs('videoJSplayer', {
+            ...initialOptions,
+            ...options,
+        }).ready(function () {
+            // console.log('onPlayerReady', this);
```
Comment (aestene) [inline frontend/src/components/VideoStream/Video.tsx:30]: Comment

**Review by GodVenn — APPROVED** [review]
LGTM
