### PR TITLE
Don't hardcode mission status

### LINKED ISSUE #2510: Isar can accept two mission if slow stopping
**Describe the bug**
If adding two missions to queue while robot is returning home, it will accept both if stopping is a bit slow. Should only accept one. Result is that flotilla gets 2 ongoing missions but only one of them will run and complete. The second one will get stuck in ongoing.

**To Reproduce**
1. Add a sleep at the beginning of stop function in isar-robot
2. Add two missions in queue while state is returning home

**Expected behavior**
Should give conflict for one of the missions. Should one accept one

**Screenshots**
Resulting logs
Image

### PR DESCRIPTION
**Pull request by andchiind**
Closes #2510 

Wait for confirmation from ISAR that the mission has started. The main "breaking change" is that missions won't show as in progress until we get a mission status event from ISAR. To accomodate this we now treat NotStarted differently from not having received any status from ISAR. This goes in hand with this ISAR PR https://github.com/equinor/isar/pull/1034.

## Ready for review checklist:
- [x] A self-review has been performed
- [x] All commits run individually
- [x] Temporary changes have been removed, like console.log, TODO, etc.
- [x] The PR has been tested locally
- [ ] A test have been written
  - [x] This change doesn't need a new test
- [x] Relevant issues are linked
- [x] Remaining work is documented in issues
  - [ ] There is no remaining work from this PR that require new issues
- [x] The changes does not introduce dead code as unused imports, functions etc.

### CODE REVIEW

File: backend/api/EventHandlers/MqttEventHandler.cs [hunk 1]
```diff
@@ -710,31 +710,6 @@ private async void OnIsarStartup(object? sender, MqttReceivedArgs mqttArgs)
                 robot.Name,
                 robot.IsarId
             );
-            try
-            {
-                await MissionScheduling.MoveCurrentMissionRunBackToQueue(robot.Id);
```
Comment (Eddasol) [inline backend/api/EventHandlers/MqttEventHandler.cs]: Do we have an alternative way to handle "re-scheduling" of missions when isar restarts?

Comment (andchiind) [reply backend/api/EventHandlers/MqttEventHandler.cs]: No, the mission would be considered failed, and ISAR should stop the mission. If we want to reschedule it, then ISAR can send a "mission aborted" MQTT message.

File: backend/api/Services/MissionSchedulingService.cs [hunk 2]
```diff
@@ -272,6 +253,11 @@ await missionRunService.UpdateMissionRunProperty(
                 logger.LogWarning("{Message}", $"No mission was running for robot {robot.Id}");
             }
 
+            var ongoingMissionRunIds = ongoingMissionRuns
+                .Where(missionRun => missionRun.Id == robot.CurrentMissionId)
+                .Select(missionRun => missionRun.Id)
+                .ToList();
+
```
[the remark this answers is not in the document]
Comment (andchiind) [reply backend/api/Services/MissionSchedulingService.cs]: In that situation it would be updated to not failed once it starts again, but yeah that might be a good idea anyways.

File: backend/api/EventHandlers/MqttEventHandler.cs [hunk 3]
```diff
@@ -706,35 +705,10 @@ private async void OnIsarStartup(object? sender, MqttReceivedArgs mqttArgs)
             }
 
             _logger.LogInformation(
-                "Received ISAR restart event for robot {robotName} with ISAR id {isarId}. Will restart ongoing missionRun, if any, by moving it back to the queue.",
+                "Received ISAR restart event for robot {robotName} with ISAR id {isarId}.",
```
Comment (Eddasol) [inline backend/api/EventHandlers/MqttEventHandler.cs]: The entire startUpMessage can probebly removed as it doesn't do anything anymore. Suggest making a new issue to handle this
