### PR TITLE
Move arm triggers banner failed return home

### LINKED ISSUE #1466: Move robot arm triggers Return to Home Mission
**Describe the bug**
Currently when we schedule a move robot arm mission, the robot becomes busy and then goes back to available. As a consequence the backend will try to schedule a return to home mission because the mission queue is empty. Since the robot current area is null, an error message is sent to the frontend saying "unable to schedule return to home mission". 

**To Reproduce**
Schedule a move arm mission for robot.

**Expected behavior**
Moving the robot arm should not trigger a return to home mission.

Suggested solution: Create a new mission type: "Move arm". Also relevant for other mission types: "Return home", "Localization".

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by mrica-equinor**
Closes #1466

### CODE REVIEW

File: backend/api/EventHandlers/MqttEventHandler.cs [hunk 1]
```diff
@@ -255,7 +256,13 @@ private async void OnIsarMissionUpdate(object? sender, MqttReceivedArgs mqttArgs
 
             if (flotillaMissionRun.IsLocalizationMission())
             {
-                if (flotillaMissionRun.Status != MissionStatus.Successful) { await robotService.UpdateCurrentArea(robot.Id, null); }
+                if (flotillaMissionRun.Status != MissionStatus.Successful)
+                {
+                    await robotService.UpdateCurrentArea(robot.Id, null);
+
+                    signalRService.ReportGeneralFailToSignalR(robot, "Failed Localization Mission", $"Failed localization mission for robot {robot.Name}.");
```
Comment (oysand) [inline backend/api/EventHandlers/MqttEventHandler.cs:263]: Should we have a more specific fail reported? ReportLocalizationMissionFailedToSignalR or something a long that?

Comment (mrica-equinor) [reply backend/api/EventHandlers/MqttEventHandler.cs:263]: We used to but then the format that is being sent inside the funtion is the same for all cases, that's why I created this general one that we can call and personalize the content with the second and third field. Otherwise we would have like 3 or more functions with different names that do exactly the same thing

File: backend/api/Services/MissionSchedulingService.cs [hunk 2]
```diff
@@ -55,10 +55,17 @@ public async Task StartNextMissionRunIfSystemIsAvailable(string robotId)
                 logger.LogInformation("The robot was ready to start mission, but no mission is scheduled");
                 if (robot.MissionQueueFrozen) { return; }
 
+                if (!await localizationService.RobotIsLocalized(robotId))
+                {
+                    string infoMessage = $"Not scheduling a return to home mission as the robot {robotId} is not localized.";
```
Comment (oysand) [inline backend/api/Services/MissionSchedulingService.cs:60]: Can this be written directly in the LogInformation?

Comment (andchiind) [reply backend/api/Services/MissionSchedulingService.cs:60]: I personally think it's good to reduce line length for readability.

Comment (mrica-equinor) [reply backend/api/Services/MissionSchedulingService.cs:60]: Don't have a strong preference on this

Comment (oysand) [reply backend/api/Services/MissionSchedulingService.cs:60]: Me neither, can keep it as it is then

File: backend/api/Services/MissionSchedulingService.cs [hunk 3]
```diff
@@ -55,10 +55,17 @@ public async Task StartNextMissionRunIfSystemIsAvailable(string robotId)
                 logger.LogInformation("The robot was ready to start mission, but no mission is scheduled");
                 if (robot.MissionQueueFrozen) { return; }
 
+                if (!await localizationService.RobotIsLocalized(robotId))
```
Comment (oysand) [inline backend/api/Services/MissionSchedulingService.cs:58]: Do we have this covered in a test or should we write one to see what happens if the robot is not localized and robot available is triggered?

Comment (mrica-equinor) [reply backend/api/Services/MissionSchedulingService.cs:58]: Test has been added

**Review by andchiind — APPROVED** [review]
LGTM
