### PR TITLE
Fix old missions in queue on isar restart

### LINKED ISSUE #2660: CurrentMissionId doesn't become null after mission
**Describe the bug**
When a mission completes the CurrentMissionId gets set to null by calling `await RobotService.UpdateCurrentMissionId(robot.Id, null);` on line 553 in MqttEventHandler.cs.

When I then call the "/robots/{id}" endpoint the currentMissionId is not null.

**To Reproduce**
1. Run mission
2. Wait for mission to complete
3. Call "/robots/{id}" endpoint and note currentMissionId

**Expected behavior**
CurrentMissionId should be null after a mission

**Screenshots**

### PR DESCRIPTION
**Pull request by Eddasol**
## Ready for review checklist:
- [ ] A self-review has been performed
- [ ] All commits run individually
- [ ] Temporary changes have been removed, like console.log, TODO, etc.
- [ ] The PR has been tested locally
- [ ] A test has been written
  - [ ] This change doesn't need a new test
- [ ] Relevant issues are linked
- [ ] Remaining work is documented in issues
  - [ ] There is no remaining work from this PR that require new issues
- [ ] The changes does not introduce dead code as unused imports, functions etc.

### CODE REVIEW

File: backend/api/EventHandlers/MqttEventHandler.cs [hunk 1]
```diff
@@ -550,6 +552,7 @@ private async void OnIsarMissionUpdate(IsarMissionMessage isarMission)
             if (robot.CurrentMissionId == flotillaMissionRun.Id)
             {
                 await RobotService.UpdateCurrentMissionId(robot.Id, null);
+                robot.CurrentMissionId = null;
```
Comment (andchiind) [inline backend/api/EventHandlers/MqttEventHandler.cs:555]: Is this change being committed to the database anywhere?

Comment (Eddasol) [reply backend/api/EventHandlers/MqttEventHandler.cs:555]: Its being comited to the database in the function on the line above. This is only to ensure that the value is updated incase the its used more within this function

**Review by nicholasdalhaug — APPROVED** [review]
